myproject/account/urls.py
from django.conf.urls import url

from .import views

app_name = "account"
urlpatterns = [
    url(r"^login/$", views.user_login, name="login"),
    url(r"^user-register/$", views.user_register, name="user_register"),
    url(r"^reg/$", views.reg, name="reg"),
    url(r"^login-for-medal/$", views.login_for_medal, name="login_for_medal"),
    url(r"^logout/$", views.logout, name="logout"),
    url(r"user-info/$", views.user_info, name="user_info"),
    url(r"^change-nickname/$", views.change_nickname, name="change_nickname"),
    url(r"^bind-email/$", views.bind_email, name="bind_email"),
    url(r"^change-password/$", views.change_password, name="change_password"),
    url(r"^forgot-password/$", views.forgot_password, name="forgot_password"),
    url(r"^send-verification-code/$", views.send_verification_code, name="send_verification_code"),
]

myproject/blog/urls.py
from django.conf.urls import url
from .import views
from django.urls import path


app_name = "blog"
urlpatterns = [
    url(r"^all-blogs/$", views.blog_list, name="all_blogs"),
    # url(r"^blog-detail/(?P<blog_id>\d+)/$", views.blog_detail, name="blog_detail"),
    path('<int:blog_pk>', views.blog_detail, name="blog_detail"),
    path('type/<int:blog_type_pk>', views.blog_with_type, name="blog_with_type"),

]



myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),

    url(r'^ckeditor', include('ckeditor_uploader.urls')),
    url(r"^blog/", include("blog.urls", namespace="blog")),
    url(r"^comment/", include("comment.urls", namespace="comment")),
    url(r"^account/", include("account.urls", namespace="account")),
    url(r"^likes/", include("likes.urls", namespace="likes")),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myproject/templates/error.html
{% extends 'header.html'%}

{% block content %}
{{ message }}, <a href="{{ redirect_to }}">返回</a>
{% endblock %}

myproject/templates/form.html
{% extends 'header.html'%}
{% block title %}{{ page_title }}{% endblock %}
{% block header_extends %}{% endblock %}

{% block content %}
<div class="containter">
    <div class="row">
        <div class="col-xs-4 col-xs-offset-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">{{ form_title }}</h3>
                </div>
                <div class="panel-body">
                    <form action="" method="post">
                        {% csrf_token %}
                        {% for field in form %}
                            {% if not field.is_hidden %}
                                <label for="{{ field.id_for_label }}"></label>
                            {% endif %}
                                {{ field }}
                            <p class="text-danger">{{ field.errors.as_text }}</p>

                        {% endfor %}
                        <span id="tip" class="text-danger">{{ register_form.errors.non_field_errors }}</span>
                        <div class="clearfix"></div>
                        <div class="pull-left">
                            {% block other_buttons %}{% endblock %}
                        </div>
                        <div class="pull-right">


                            <button class="btn btn-default" onclick="window.location.href='{{ return_back_url }}'">返回</button>
                        </div>
                        <div class="pull-right">
                            <input type="submit" class="btn btn-primary pull-right" value="{{ submit_text }}">
                        </div>
                    </form>
                </div>
        </div>
    </div>

</div>



{% endblock %}

myproject/templates/header.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load staticfiles %}
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <script type="text/javascript" rel="stylesheet" src="{% static 'js/jquery-3.0.0.min.js'%}"></script>
    <script type="text/javascript" rel="stylesheet" src="{% static 'js/bootstrap.min.js'%}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css'%}">
    {% block header_extends %}{% endblock %}
</head>
<body>
<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav">
        <li class="active"><a href="#">首页 <span class="sr-only">(current)</span></a></li>
        <li><a href="{% url 'blog:all_blogs'%}">全部文章</a></li>
        <li><a href="http://127.0.0.1:8000/blog/type/1">玄幻小说</a></li>
        <li><a href="http://127.0.0.1:8000/blog/type/3">修真</a></li>
        <li><a href="http://127.0.0.1:8000/blog/type/2">科幻</a></li>

        <li><a href="{% url 'account:reg'%}">垃圾</a></li>
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
               aria-expanded="false">Dropdown <span class="caret"></span></a>
            <ul class="dropdown-menu">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="#">Separated link</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="#">One more separated link</a></li>
            </ul>
        </li>
    </ul>
    <form class="navbar-form navbar-left">
        <div class="form-group">
            <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
    </form>

    <ul class="nav navbar-nav navbar-right">

        {% if not user.is_authenticated %}
        <li><a href="{% url 'account:login'%}?from={{ request.get_full_path }}">登录</a></li>
        <li><a href="{% url 'account:user_register'%}?from={{ request.get_full_path}}">注册</a></li>
        {% else %}
        <li><a>用户名：
            {% if user.has_nickname %}
                {{ user.username }}({{ user.get_nickname }})
            {% else %}
                {{ user.username }}
            {% endif %}
        </a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" >用户信息<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="{% url 'account:user_info'%}">个人资料</a>
              <li><a href="{% url 'account:change_password'%}">修改密码</a></li>
            <li><a href="#">后台管理</a></li>
            <li><a href="#"></a></li>
            <li role="separator" class="divider"></li>
            <li><a href="{% url 'account:logout'%}?from={{ request.get_full_path }}">退出登录</a></li>
          </ul>
        </li>

        {% endif %}

    </ul>
</div><!-- /.navbar-collapse -->
{% block content %}{% endblock %}
{% block script_extends %}{% endblock %}

</body>
</html>