myproject/blog/urls.py
from django.conf.urls import url
from .import views
from django.urls import path


app_name = "blog"
urlpatterns = [
    url(r"^all-blogs/$", views.blog_list, name="all_blogs"),
    # url(r"^blog-detail/(?P<blog_id>\d+)/$", views.blog_detail, name="blog_detail"),
    path('<int:blog_pk>', views.blog_detail, name="blog_detail"),
    path('type/<int:blog_type_pk>', views.blog_with_type, name="blog_with_type"),

]



myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),

    url(r'^ckeditor', include('ckeditor_uploader.urls')),
    url(r"^blog/", include("blog.urls", namespace="blog")),
    url(r"^comment/", include("comment.urls", namespace="comment")),
    url(r"^account/", include("account.urls", namespace="account")),
    url(r"^likes/", include("likes.urls", namespace="likes")),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myproject/blog/models.py
from django.db import models
from django.contrib.auth.models import User
#
# 错误集合
from django.db.models.fields import exceptions
from ckeditor_uploader.fields import RichTextUploadingField


# Create your models here.
class BlogType(models.Model):
    type_name = models.CharField(max_length=50, verbose_name="博客类型")

    class Meta:
        verbose_name = verbose_name_plural = "博客类型"

    def __str__(self):
        return self.type_name

    objects = models.Manager()


class Blog(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="作者")
    title = models.CharField(max_length=50, verbose_name="标题")
    content = RichTextUploadingField(verbose_name="内容")
    # readed_num = models.IntegerField(default=0)
    created_time = models.DateTimeField(auto_now_add=True, verbose_name="创建时间")
    last_updated_time = models.DateTimeField(auto_now=True, verbose_name="更新时间")
    blog_type = models.ForeignKey(BlogType, on_delete=models.CASCADE, verbose_name="所属博客类型")

    # 返回值
    def get_read_num(self):
        try:
            return self.readnum.read_num

        # 对象不存在
        except exceptions.ObjectDoesNotExist :
            return 0

    class Meta:
        verbose_name = verbose_name_plural = "博客信息"
        ordering = ("-created_time",)

    def __str__(self):
        return self.title

    objects = models.Manager()


class ReadNum(models.Model):
    blog = models.OneToOneField(Blog, on_delete=models.DO_NOTHING, verbose_name="阅读所属文章")
    read_num = models.IntegerField(default=0, verbose_name="阅读次数")

    class Meta:
        verbose_name = verbose_name_plural = "阅读次数"



    objects = models.Manager()

myproject/blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import BlogType, Blog, ReadNum
from django.core.paginator import Paginator
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
from django.urls import reverse
from django.contrib.contenttypes.models import ContentType
from comment.models import Comment
from comment.forms import CommentForm
from account.forms import LoginForm
from django.http import JsonResponse

# 引入缓存
from django.core.cache import caches


# Create your views here.
def blog_list(request):
    all_blogs_list = Blog.objects.all()
    paginator = Paginator(all_blogs_list, 2)
    page_num = request.GET.get("page", 1)
    # get_page方法用于控制不是数字类型，默认返回页面1
    page_of_blogs = paginator.get_page(page_num)

    # 获取当前页
    current_page_num = page_of_blogs.number

    # 获取前后四页的范围
    page_range = list(range(max(current_page_num - 3, 1), current_page_num)) + \
                 list(range(current_page_num, min(current_page_num + 3, paginator.num_pages) + 1))

    # 加上省略标记
    if page_range[0] - 1 >= 4:
        page_range.insert(0, "...")
    if paginator.num_pages - page_range[-1] >= 4:
        page_range.append('...')

    # 加上首页和尾页
    if page_range[0] != 1:
        page_range.insert(0, 1)

    if page_range[-1] != paginator.num_pages:
        page_range.append(paginator.num_pages)

    context = {}
    context["page_of_blogs"] = page_of_blogs
    context["page_range"] = page_range

    # 上面有了，所以不需要下面这句
    # context["blogs"] = Blog.objects.all()
    context["blogs_num"] = Blog.objects.all().count()
    return render(request, 'blog/all_blog.html', context)


def blog_detail(request, blog_pk):
    context = {}
    blog = get_object_or_404(Blog,pk=blog_pk)
    # 方法一
    # blog.readed_num += 1
    # blog.save()

    # 方法二

    if ReadNum.objects.filter(blog=blog).count():
        # 存在记录
        readnum = ReadNum.objects.get(blog=blog)
    else:
        readnum = ReadNum(blog=blog)

    readnum.read_num += 1
    readnum.save()

    # 获取评论
    # blog_content_type = ContentType.objects.get_for_model(blog)
    # comments = Comment.objects.filter(content_type=blog_content_type, object_id=blog.pk, parent=None)

    context["previous_blog"] = Blog.objects.filter(created_time__gt=blog.created_time).last()
    context["next_blog"] = Blog.objects.filter(created_time__lt=blog.created_time).first()
    context["blog"] = blog
    context["login_form"] = LoginForm()
    # 设置回复倒叙
    # context["comments"] = comments.order_by('-comment_time')

    # context["comments_count"] = Comment.objects.filter(content_type=blog_content_type, object_id=blog.pk).count()
    data = {}
    # 获取对象的model
    # data["content_type"] = blog_content_type.model
    # data["object_id"] = blog_pk
    # 在前端初始化值
    # context["comment_form"] = CommentForm(initial={"content_type": blog_content_type.model, "object_id": blog_pk, "reply_comment_id": 0})
    return render(request, 'blog/blog_detail.html', context)


def blog_with_type(request, blog_type_pk):
    context = {}
    blog_type = get_object_or_404(BlogType, pk=blog_type_pk)
    all_blogs_list = Blog.objects.filter(blog_type=blog_type)
    paginator = Paginator(all_blogs_list, 2)
    page_num = request.GET.get("page", 1)
    # get_page方法用于控制不是数字类型，默认返回页面1
    page_of_blogs = paginator.get_page(page_num)

    # 获取当前页
    current_page_num = page_of_blogs.number

    # 获取前后四页的范围
    page_range = list(range(max(current_page_num - 3, 1), current_page_num)) + \
                 list(range(current_page_num, min(current_page_num + 3, paginator.num_pages) + 1))

    # 加上省略标记
    if page_range[0] - 1 >= 4:
        page_range.insert(0, "...")
    if paginator.num_pages - page_range[-1] >= 4:
        page_range.append('...')

    # 加上首页和尾页
    if page_range[0] != 1:
        page_range.insert(0, 1)

    if page_range[-1] != paginator.num_pages:
        page_range.append(paginator.num_pages)

    context["blogs"] = Blog.objects.filter(blog_type=blog_type)
    context["blogs_num"] = Blog.objects.filter(blog_type=blog_type).count()
    context["blog_type"] = blog_type
    context["page_of_blogs"] = page_of_blogs
    context["page_range"] = page_range
    return render(request, 'blog/blog_with_type.html', context)






myproject/templates/blog/all_blog.html
<!DOCTYPE html>
<html lang="en">
<head>

    {% extends 'header.html'%}
    {% load staticfiles %}
    {% load comment_tags %}
    {% load likes_tags %}
    <meta charset="UTF-8">
    <title>{% block title %}全部文章{% endblock%}</title>
    {% block header_extends %}
        <script type="text/javascript" rel="stylesheet" src="{% static 'js/jquery-3.0.0.min.js'%}"></script>
    <script type="text/javascript" rel="stylesheet" src="{% static 'js/bootstrap.min.js'%}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css'%}">
    {% endblock %}
</head>
<body>
{% block content %}
<div class="containter">
    <div class="row">
        <div class="col-xs-10 col-xs-offset-2">
            <span>共有{{ blogs_num }}篇文章</span>
            <p><span>共有{{ page_of_blogs.paginator.count}}博客</span></p>

            <!--                object_list  这一页里面的数量-->
            {% for blog in page_of_blogs.object_list %}
            <h3><a href="{% url 'blog:blog_detail' blog.pk %}">标题：{{ blog.title }}</a></h3>
            <span style="font-size:12px">类型：{{ blog.blog_type }}</span>

<!--            striptags   去掉标签，保留内容-->
            <p>{{ blog.content|striptags|truncatechars:15}}</p>
            <span>作者：{{ blog.author }}</span>
            <span>创建时间：{{ blog.created_time }}</span>
            <span>阅读次数：({{ blog.get_read_num }})</span>
            <span>评论数量：({% get_comment_count blog %})</span>
            <span>点赞：({% get_likes_count blog %})</span>
            {% empty %}
            <span>暂时没有文章</span>
            {% endfor %}

            <div>
                <ul class="pagination">

                    <li>
                        {% if page_of_blogs.has_previous %}
                        <a href="?page={{ page_of_blogs.previous_page_number }}" aria-label="Previous">
                            上一页<span aria-hidden="true">&laquo;</span>
                        </a>

                        {% else %}
                        <span aria-hidden="true">&laquo;</span>
                        {% endif %}
                    </li>


                    <!--            遍历循环出页数-->
                    {% for page_num in page_range %}
                    <!--                        判断是否当前页,高亮-->
                    {% if page_num == page_of_blogs.number %}
                    <li class="active"><a href="?page={{ page_num }}">{{ page_num }}</a></li>
                    {% else %}
                    <li><a href="?page={{ page_num }}">{{ page_num }}</a></li>
                    {% endif %}


                    {% endfor %}
                    <li>
                        {% if page_of_blogs.has_next %}
                        <a href="?page={{ page_of_blogs.next_page_number }}" aria-label="Next">
                            下一页<span aria-hidden="true">&laquo;</span>
                            {% else %}
                            <span aria-hidden="true">&laquo;</span>
                            {% endif %}

                    </li>
                </ul>
                <div style="color:orange;">
                    <p>共有{{ page_of_blogs.paginator.count}}文章,当前第{{ page_of_blogs.number }}页,
                        共有{{ page_of_blogs.paginator.num_pages }}页
                    </p>

                </div>

            </div>
        </div>


    </div>

</div>
{% endblock %}
</body>
</html>

myproject/templates/blog/blog_with_type.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% extends 'header.html'%}
    <meta charset="UTF-8">
    <title>{{ blog_type.blog_name }}</title>
    {% block header_extends %}{% endblock %}
</head>
<body>
{% block content %}
<div class="containter">
    <div class="row">
        <div class="col-xs-6 col-xs-offset-3">
            <!--             <p> <span>共有{{ blogs|length}}博客</span></p>-->
            <span style="font-size:18px;color:orange;border-bottom:1px dashed pink;">共有{{ blogs_num }}篇{{ blog_type.type_name }}</span>

            {% for blog in page_of_blogs.object_list %}
            <h3><a href="{% url 'blog:blog_detail' blog.id %}">标题：{{ blog.title }}</a></h3>
            <span style="font-size:12px">类型：{{ blog.blog_type }}</span>
            <p>{{ blog.content|truncatechars:15}}</p>
            <span>作者：{{ blog.author }}</span>
            {% empty %}
            <span>暂时没有文章</span>
            {% endfor %}
            <div>
                <ul class="pagination">

                    <li>
                        {% if page_of_blogs.has_previous %}
                        <a href="?page={{ page_of_blogs.previous_page_number }}" aria-label="Previous">
                            上一页<span aria-hidden="true">&laquo;</span>
                        </a>

                        {% else %}
                        <span aria-hidden="true">&laquo;</span>
                        {% endif %}
                    </li>


                    <!--            遍历循环出页数-->
                    {% for page_num in page_range %}
                    <!--                        判断是否当前页,高亮-->
                    {% if page_num == page_of_blogs.number %}
                    <li class="active"><a href="?page={{ page_num }}">{{ page_num }}</a></li>
                    {% else %}
                    <li><a href="?page={{ page_num }}">{{ page_num }}</a></li>
                    {% endif %}


                    {% endfor %}
                    <li>
                        {% if page_of_blogs.has_next %}
                        <a href="?page={{ page_of_blogs.next_page_number }}" aria-label="Next">
                            下一页<span aria-hidden="true">&laquo;</span>
                            {% else %}
                            <span aria-hidden="true">&laquo;</span>
                            {% endif %}

                    </li>
                </ul>
                <div style="color:orange;">
                    <p>共有{{ page_of_blogs.paginator.count}}文章,当前第{{ page_of_blogs.number }}页,
                        共有{{ page_of_blogs.paginator.num_pages }}页
                    </p>

                </div>
            </div>
        </div>
    </div>

    {% endblock %}

</body>
</html>